import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | undefined;
export type InputMaybe<T> = T | undefined;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  ISO8601DateTime: { input: string; output: string; }
};

export type ActionEnum =
  | 'addAlbum'
  | 'addArtist'
  | 'addPlaylistItems'
  | 'addRole'
  | 'album'
  | 'albums'
  | 'allActions'
  | 'appleMusicToken'
  | 'artist'
  | 'artists'
  | 'changeAlbumStatus'
  | 'changeArtistStatus'
  | 'changeFavorites'
  | 'changePassword'
  | 'clearCache'
  | 'console'
  | 'defineTypes'
  | 'deletePlaylist'
  | 'forceIgnoreAlbum'
  | 'graphiql'
  | 'ignoreAlbums'
  | 'ignoreArtists'
  | 'login'
  | 'logout'
  | 'me'
  | 'playlist'
  | 'playlists'
  | 'roles'
  | 'signup'
  | 'track'
  | 'tracks'
  | 'updateAlbum'
  | 'updateMe'
  | 'updateRole'
  | 'upsertPlaylist';

/** Autogenerated input type of AddAlbum */
export type AddAlbumInput = {
  /** Apple Music か iTunes のアルバムを登録 */
  readonly appleMusicId: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of AddAlbum */
export type AddAlbumPayload = {
  /** 追加されたアルバム */
  readonly album?: Maybe<AlbumObject>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of AddArtist */
export type AddArtistInput = {
  /** アーティストを登録 */
  readonly appleMusicId: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of AddArtist */
export type AddArtistPayload = {
  /** 追加されたアーティスト */
  readonly artist?: Maybe<ArtistObject>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of AddPlaylistItems */
export type AddPlaylistItemsInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** プレイリストID */
  readonly playlistId: Scalars['String']['input'];
  /** 追加したい曲ID */
  readonly trackIds: ReadonlyArray<Scalars['String']['input']>;
};

/** Autogenerated return type of AddPlaylistItems */
export type AddPlaylistItemsPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  /** 曲追加されたプレイリスト */
  readonly playlist?: Maybe<PlaylistObject>;
};

/** Autogenerated input type of AddRole */
export type AddRoleInput = {
  /** 変更したいアクション。全て上書きされる。IDを指定しない場合は必須。 */
  readonly allowedActions: ReadonlyArray<ActionEnum>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** ロールの説明。IDを指定しない場合は必須。 */
  readonly description: Scalars['String']['input'];
  /** ロール名。IDを指定しない場合は必須。 */
  readonly name: Scalars['String']['input'];
};

/** Autogenerated return type of AddRole */
export type AddRolePayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  /** 追加更新されたロール */
  readonly role?: Maybe<RoleObject>;
};

/** アルバム */
export type AlbumObject = {
  /** Apple Music ID */
  readonly appleMusicId: Scalars['String']['output'];
  /** iTunes 判定 */
  readonly appleMusicPlayable: Scalars['Boolean']['output'];
  /** 大型アートワーク */
  readonly artworkL?: Maybe<ArtworkObject>;
  /** 中型アートワーク */
  readonly artworkM?: Maybe<ArtworkObject>;
  /** コピーライト */
  readonly copyright: Scalars['String']['output'];
  /** 追加日 */
  readonly createdAt: Scalars['ISO8601DateTime']['output'];
  /** ID */
  readonly id: Scalars['String']['output'];
  /** タイトル */
  readonly name: Scalars['String']['output'];
  /** レーベル */
  readonly recordLabel: Scalars['String']['output'];
  /** 発売日 */
  readonly releaseDate: Scalars['ISO8601DateTime']['output'];
  /** ステータス */
  readonly status: StatusEnum;
  /** トラック数 */
  readonly totalTracks: Scalars['Int']['output'];
  /** トラック */
  readonly tracks: ReadonlyArray<TrackObject>;
  /** upc */
  readonly upc: Scalars['String']['output'];
};

export type AlbumsConditionsInputObject = {
  /** アーティストID */
  readonly artistIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  /** お気に入り */
  readonly favorite?: InputMaybe<Scalars['Boolean']['input']>;
  /** アルバム名(あいまい検索) */
  readonly name?: InputMaybe<Scalars['String']['input']>;
  /** 表示ステータス */
  readonly status?: InputMaybe<ReadonlyArray<StatusEnum>>;
  /** トラックID */
  readonly trackIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
};

export type AlbumsQueryOrderEnum =
  /** 追加順 */
  | 'NEW'
  /** 人気順 */
  | 'POPULARITY'
  /** 発売日順 */
  | 'RELEASE';

export type AlbumsSortInputObject = {
  /** 並び順 */
  readonly direction?: InputMaybe<SortEnum>;
  /** 並び順対象 */
  readonly order?: InputMaybe<AlbumsQueryOrderEnum>;
};

/** アーティスト */
export type ArtistObject = {
  /** 大型アートワーク */
  readonly artworkL: ArtworkObject;
  /** 中型アートワーク */
  readonly artworkM: ArtworkObject;
  /** 追加日 */
  readonly createdAt: Scalars['ISO8601DateTime']['output'];
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 名前 */
  readonly name: Scalars['String']['output'];
  /** 発売日 */
  readonly releaseDate: Scalars['ISO8601DateTime']['output'];
  /** ステータス */
  readonly status: StatusEnum;
};

export type ArtistsConditionsInputObject = {
  /** アルバムID */
  readonly albumIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  /** お気に入り */
  readonly favorite?: InputMaybe<Scalars['Boolean']['input']>;
  /** アーティスト名(あいまい検索) */
  readonly name?: InputMaybe<Scalars['String']['input']>;
  /** 表示ステータス */
  readonly status?: InputMaybe<ReadonlyArray<StatusEnum>>;
  /** トラックID */
  readonly trackIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
};

export type ArtistsQueryOrderEnum =
  /** 名前順 */
  | 'NAME'
  /** 追加順 */
  | 'NEW'
  /** 人気順 */
  | 'POPULARITY';

export type ArtistsSortInputObject = {
  /** 並び順 */
  readonly direction?: InputMaybe<SortEnum>;
  /** 並び順対象 */
  readonly order?: InputMaybe<ArtistsQueryOrderEnum>;
};

/** アートワーク */
export type ArtworkObject = {
  /** 高さ */
  readonly height?: Maybe<Scalars['Int']['output']>;
  /** URL */
  readonly url?: Maybe<Scalars['String']['output']>;
  /** 幅 */
  readonly width?: Maybe<Scalars['Int']['output']>;
};

/** Autogenerated input type of ChangeAlbumStatus */
export type ChangeAlbumStatusInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 変更したいID */
  readonly id: Scalars['String']['input'];
  /** 変更したいステータス */
  readonly status: StatusEnum;
  /** ツイートするか */
  readonly tweet: Scalars['Boolean']['input'];
};

/** Autogenerated return type of ChangeAlbumStatus */
export type ChangeAlbumStatusPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result: Scalars['Boolean']['output'];
};

/** Autogenerated input type of ChangeArtistStatus */
export type ChangeArtistStatusInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 変更したいID */
  readonly id: Scalars['String']['input'];
  /** 変更したいステータス */
  readonly status: StatusEnum;
};

/** Autogenerated return type of ChangeArtistStatus */
export type ChangeArtistStatusPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result: Scalars['Boolean']['output'];
};

/** Autogenerated input type of ChangeFavorites */
export type ChangeFavoritesInput = {
  /** お気に入り変更したいアルバムID */
  readonly albumIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  /** お気に入り変更したいアーティストID */
  readonly artistIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** true の場合は一括でお気に入り登録をする。false 場合は一括で解除する。 */
  readonly favorite: Scalars['Boolean']['input'];
  /** お気に入り変更したいプレイリストID */
  readonly playlistIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
  /** お気に入り変更したいトラックID */
  readonly trackIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
};

/** Autogenerated return type of ChangeFavorites */
export type ChangeFavoritesPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  /** 更新されたカレントユーザー */
  readonly currentUser?: Maybe<CurrentUserObject>;
};

/** Autogenerated input type of ChangePassword */
export type ChangePasswordInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  readonly currentPassword: Scalars['String']['input'];
  readonly newPassword: Scalars['String']['input'];
  readonly newPasswordConfirmation: Scalars['String']['input'];
};

/** Autogenerated return type of ChangePassword */
export type ChangePasswordPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly currentUser?: Maybe<CurrentUserObject>;
};

/** Autogenerated input type of ClearCache */
export type ClearCacheInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of ClearCache */
export type ClearCachePayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result?: Maybe<ReadonlyArray<Scalars['String']['output']>>;
};

/** カレントユーザー */
export type CurrentUserObject = {
  /** お気に入り */
  readonly favorite: FavoriteObject;
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 名前 */
  readonly name: Scalars['String']['output'];
  /** 登録済み */
  readonly registered: Scalars['Boolean']['output'];
  /** ロール */
  readonly role: RoleObject;
  /** ユーザー名 */
  readonly username: Scalars['String']['output'];
};

export type CursorInputObject = {
  readonly limit?: InputMaybe<Scalars['Int']['input']>;
  readonly offset?: InputMaybe<Scalars['Int']['input']>;
};

/** Autogenerated input type of DeletePlaylist */
export type DeletePlaylistInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  readonly playlistId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of DeletePlaylist */
export type DeletePlaylistPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result?: Maybe<Scalars['Boolean']['output']>;
};

/** お気に入り */
export type FavoriteObject = {
  /** アルバムID */
  readonly albumIds: ReadonlyArray<Scalars['String']['output']>;
  /** アーティストID */
  readonly artistIds: ReadonlyArray<Scalars['String']['output']>;
  /** プレイリストID */
  readonly playlistIds: ReadonlyArray<Scalars['String']['output']>;
  /** トラックID */
  readonly trackIds: ReadonlyArray<Scalars['String']['output']>;
};

/** Autogenerated input type of ForceIgnoreAlbum */
export type ForceIgnoreAlbumInput = {
  /** 除外コンテンツに登録したいアルバムID */
  readonly albumId: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of ForceIgnoreAlbum */
export type ForceIgnoreAlbumPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result: Scalars['Boolean']['output'];
};

/** Autogenerated input type of IgnoreAlbums */
export type IgnoreAlbumsInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of IgnoreAlbums */
export type IgnoreAlbumsPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result?: Maybe<Scalars['Boolean']['output']>;
};

/** Autogenerated input type of IgnoreArtists */
export type IgnoreArtistsInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of IgnoreArtists */
export type IgnoreArtistsPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly result?: Maybe<Scalars['Boolean']['output']>;
};

/** Autogenerated input type of Login */
export type LoginInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  readonly currentPassword: Scalars['String']['input'];
  readonly username: Scalars['String']['input'];
};

/** Autogenerated return type of Login */
export type LoginPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly currentUser?: Maybe<CurrentUserObject>;
};

/** Autogenerated input type of Logout */
export type LogoutInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of Logout */
export type LogoutPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly currentUser?: Maybe<CurrentUserObject>;
};

export type Mutation = {
  /** アルバムを追加する */
  readonly addAlbum?: Maybe<AddAlbumPayload>;
  /** アーティストを追加する */
  readonly addArtist?: Maybe<AddArtistPayload>;
  /** プレイリストに曲を追加する */
  readonly addPlaylistItems?: Maybe<AddPlaylistItemsPayload>;
  /** ロールを追加する */
  readonly addRole?: Maybe<AddRolePayload>;
  /** アルバムステータス変更 */
  readonly changeAlbumStatus?: Maybe<ChangeAlbumStatusPayload>;
  /** アーティストステータス変更 */
  readonly changeArtistStatus?: Maybe<ChangeArtistStatusPayload>;
  /** お気に入り一括変更 */
  readonly changeFavorites?: Maybe<ChangeFavoritesPayload>;
  /** パスワード変更 */
  readonly changePassword?: Maybe<ChangePasswordPayload>;
  /** 検索結果キャッシュをリセットする */
  readonly clearCache?: Maybe<ClearCachePayload>;
  /** プレイリストを削除する */
  readonly deletePlaylist?: Maybe<DeletePlaylistPayload>;
  /** 対象アルバムを除外コンテンツに登録する */
  readonly forceIgnoreAlbum?: Maybe<ForceIgnoreAlbumPayload>;
  /** PENDING状態のアルバム全てをIGNOREにする。よく考えてから実行すること。 */
  readonly ignoreAlbums?: Maybe<IgnoreAlbumsPayload>;
  /** PENDING状態のアーティスト全てをIGNOREにする。よく考えてから実行すること。 */
  readonly ignoreArtists?: Maybe<IgnoreArtistsPayload>;
  /** ログイン */
  readonly login?: Maybe<LoginPayload>;
  /** ログアウト */
  readonly logout?: Maybe<LogoutPayload>;
  /** サインアップ */
  readonly signup?: Maybe<SignupPayload>;
  /** アルバムを最新状態にする */
  readonly updateAlbum?: Maybe<UpdateAlbumPayload>;
  /** カレントユーザー情報更新 */
  readonly updateMe?: Maybe<UpdateMePayload>;
  /** ロールを追加更新する */
  readonly updateRole?: Maybe<UpdateRolePayload>;
  /** プレイリストを作成更新する */
  readonly upsertPlaylist?: Maybe<UpsertPlaylistPayload>;
};


export type Mutation_AddAlbumArgs = {
  input: AddAlbumInput;
};


export type Mutation_AddArtistArgs = {
  input: AddArtistInput;
};


export type Mutation_AddPlaylistItemsArgs = {
  input: AddPlaylistItemsInput;
};


export type Mutation_AddRoleArgs = {
  input: AddRoleInput;
};


export type Mutation_ChangeAlbumStatusArgs = {
  input: ChangeAlbumStatusInput;
};


export type Mutation_ChangeArtistStatusArgs = {
  input: ChangeArtistStatusInput;
};


export type Mutation_ChangeFavoritesArgs = {
  input: ChangeFavoritesInput;
};


export type Mutation_ChangePasswordArgs = {
  input: ChangePasswordInput;
};


export type Mutation_ClearCacheArgs = {
  input: ClearCacheInput;
};


export type Mutation_DeletePlaylistArgs = {
  input: DeletePlaylistInput;
};


export type Mutation_ForceIgnoreAlbumArgs = {
  input: ForceIgnoreAlbumInput;
};


export type Mutation_IgnoreAlbumsArgs = {
  input: IgnoreAlbumsInput;
};


export type Mutation_IgnoreArtistsArgs = {
  input: IgnoreArtistsInput;
};


export type Mutation_LoginArgs = {
  input: LoginInput;
};


export type Mutation_LogoutArgs = {
  input: LogoutInput;
};


export type Mutation_SignupArgs = {
  input: SignupInput;
};


export type Mutation_UpdateAlbumArgs = {
  input: UpdateAlbumInput;
};


export type Mutation_UpdateMeArgs = {
  input: UpdateMeInput;
};


export type Mutation_UpdateRoleArgs = {
  input: UpdateRoleInput;
};


export type Mutation_UpsertPlaylistArgs = {
  input: UpsertPlaylistInput;
};

/** プレイリストトラック */
export type PlaylistItemObject = {
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 曲 */
  readonly track: TrackObject;
  /** トラックナンバー */
  readonly trackNumber: Scalars['Int']['output'];
};

/** プレイリスト */
export type PlaylistObject = {
  /** 作者 */
  readonly author?: Maybe<UserObject>;
  /** 作成日 */
  readonly createdAt: Scalars['ISO8601DateTime']['output'];
  /** 説明 */
  readonly description: Scalars['String']['output'];
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 自身のプレイリストか判定 */
  readonly isMine?: Maybe<Scalars['Boolean']['output']>;
  /** 曲一覧 */
  readonly items: ReadonlyArray<PlaylistItemObject>;
  /** タイトル */
  readonly name: Scalars['String']['output'];
  /** 公開種別 */
  readonly publicType: PlaylistPublicTypeEnum;
  /** ジャケットトラック */
  readonly track?: Maybe<TrackObject>;
  /** 更新日 */
  readonly updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type PlaylistPublicTypeEnum =
  /** 匿名公開 */
  | 'ANONYMOUS_OPEN'
  /** 非公開 */
  | 'NON_OPEN'
  /** 公開 */
  | 'OPEN';

export type PlaylistsConditionsInputObject = {
  /** お気に入り */
  readonly favorite?: InputMaybe<Scalars['Boolean']['input']>;
  /** 自身のプレイリスト取得 */
  readonly isMine?: InputMaybe<Scalars['Boolean']['input']>;
  /** プレイリスト名( like 検索) */
  readonly name?: InputMaybe<Scalars['String']['input']>;
};

export type PlaylistsQueryOrderEnum =
  /** 作成日順 */
  | 'NEW'
  /** 人気順 */
  | 'POPULARITY'
  /** 更新日順 */
  | 'UPDATE';

export type PlaylistsSortInputObject = {
  /** 並び順 */
  readonly direction?: InputMaybe<SortEnum>;
  /** 並び順対象 */
  readonly order?: InputMaybe<PlaylistsQueryOrderEnum>;
};

export type Query = {
  /** アルバム情報取得 */
  readonly album?: Maybe<AlbumObject>;
  /** アルバム一覧取得 */
  readonly albums?: Maybe<ReadonlyArray<AlbumObject>>;
  /** アクション一覧取得 */
  readonly allActions: ReadonlyArray<ActionEnum>;
  /** Apple Music Token */
  readonly appleMusicToken: Scalars['String']['output'];
  /** アーティスト取得 */
  readonly artist?: Maybe<ArtistObject>;
  /** アーティスト一覧取得 */
  readonly artists?: Maybe<ReadonlyArray<ArtistObject>>;
  /** 型定義用 */
  readonly defineTypes: Scalars['Boolean']['output'];
  /** カレントユーザー情報取得 */
  readonly me: CurrentUserObject;
  /** プレイリスト取得 */
  readonly playlist?: Maybe<PlaylistObject>;
  /** プレイリスト一覧取得 */
  readonly playlists?: Maybe<ReadonlyArray<PlaylistObject>>;
  /** ロール一覧取得 */
  readonly roles: ReadonlyArray<RoleObject>;
  /** トラック情報取得 */
  readonly track?: Maybe<TrackObject>;
  /** トラック一覧取得 */
  readonly tracks?: Maybe<ReadonlyArray<TrackObject>>;
};


export type Query_AlbumArgs = {
  id: Scalars['String']['input'];
};


export type Query_AlbumsArgs = {
  conditions?: InputMaybe<AlbumsConditionsInputObject>;
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<AlbumsSortInputObject>;
};


export type Query_ArtistArgs = {
  id: Scalars['String']['input'];
};


export type Query_ArtistsArgs = {
  conditions?: InputMaybe<ArtistsConditionsInputObject>;
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<ArtistsSortInputObject>;
};


export type Query_DefineTypesArgs = {
  action: ActionEnum;
};


export type Query_PlaylistArgs = {
  id: Scalars['String']['input'];
};


export type Query_PlaylistsArgs = {
  conditions?: InputMaybe<PlaylistsConditionsInputObject>;
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<PlaylistsSortInputObject>;
};


export type Query_TrackArgs = {
  id: Scalars['String']['input'];
};


export type Query_TracksArgs = {
  conditions?: InputMaybe<TracksConditionsInputObject>;
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<TracksSortInputObject>;
};

/** ロール */
export type RoleObject = {
  /** 出来ること一覧 */
  readonly allowedActions: ReadonlyArray<ActionEnum>;
  /** 説明 */
  readonly description: Scalars['String']['output'];
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 名前 */
  readonly name: Scalars['String']['output'];
};

/** Autogenerated input type of Signup */
export type SignupInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  readonly name: Scalars['String']['input'];
  readonly newPassword: Scalars['String']['input'];
  readonly newPasswordConfirmation: Scalars['String']['input'];
  readonly username: Scalars['String']['input'];
};

/** Autogenerated return type of Signup */
export type SignupPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly currentUser?: Maybe<CurrentUserObject>;
};

export type SortEnum =
  /** 昇順 */
  | 'ASC'
  /** 降順 */
  | 'DESC';

export type StatusEnum =
  /** 有効 : 通常検索結果に表示される */
  | 'ACTIVE'
  /** 除外 : 検索結果から除外される。最新情報などを取得する際などでも除外される */
  | 'IGNORE'
  /** 保留 : デフォルトの検索結果に表示されない */
  | 'PENDING';

/** トラック */
export type TrackObject = {
  /** Apple Music ID */
  readonly appleMusicId: Scalars['String']['output'];
  /** iTunes 判定 */
  readonly appleMusicPlayable: Scalars['Boolean']['output'];
  /** 大型アートワーク */
  readonly artworkL: ArtworkObject;
  /** 中型アートワーク */
  readonly artworkM: ArtworkObject;
  /** ディスク番号 */
  readonly discNumber: Scalars['Int']['output'];
  /** 再生時間 */
  readonly durationMs: Scalars['Int']['output'];
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 国際標準レコーディングコード */
  readonly isrc: Scalars['String']['output'];
  /** タイトル */
  readonly name: Scalars['String']['output'];
  /** 人気度 */
  readonly popularity: Scalars['Int']['output'];
  /** プレビューURL */
  readonly previewUrl?: Maybe<Scalars['String']['output']>;
  /** ステータス */
  readonly status: StatusEnum;
  /** トラック番号 */
  readonly trackNumber: Scalars['Int']['output'];
};

export type TracksConditionsInputObject = {
  /** お気に入り */
  readonly favorite?: InputMaybe<Scalars['Boolean']['input']>;
  /** トラック名(あいまい検索) */
  readonly name?: InputMaybe<Scalars['String']['input']>;
  /** ランダム取得 */
  readonly random?: InputMaybe<Scalars['Boolean']['input']>;
  /** 表示ステータス */
  readonly status?: InputMaybe<ReadonlyArray<StatusEnum>>;
};

export type TracksQueryOrderEnum =
  /** 追加順 */
  | 'NEW'
  /** 人気順 */
  | 'POPULARITY';

export type TracksSortInputObject = {
  /** 並び順 */
  readonly direction?: InputMaybe<SortEnum>;
  /** 並び順対象 */
  readonly order?: InputMaybe<TracksQueryOrderEnum>;
};

/** Autogenerated input type of UpdateAlbum */
export type UpdateAlbumInput = {
  /** 指定したアルバムのトラック(ISRC)を含んでいる別音楽サービスのアルバムを一括登録 */
  readonly albumId: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateAlbum */
export type UpdateAlbumPayload = {
  /** 追加されたアルバム */
  readonly album?: Maybe<AlbumObject>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of UpdateMe */
export type UpdateMeInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  readonly name?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateMe */
export type UpdateMePayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  readonly currentUser?: Maybe<CurrentUserObject>;
};

/** Autogenerated input type of UpdateRole */
export type UpdateRoleInput = {
  /** 変更したいアクション。全て上書きされる。IDを指定しない場合は必須。 */
  readonly allowedActions?: InputMaybe<ReadonlyArray<ActionEnum>>;
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** ロールの説明。IDを指定しない場合は必須。 */
  readonly description?: InputMaybe<Scalars['String']['input']>;
  /** ロール名。IDを指定しない場合は必須。 */
  readonly name?: InputMaybe<Scalars['String']['input']>;
  /** 変更したいロール。IDを指定しない場合は追加される */
  readonly roleId: Scalars['String']['input'];
};

/** Autogenerated return type of UpdateRole */
export type UpdateRolePayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  /** 追加更新されたロール */
  readonly role?: Maybe<RoleObject>;
};

/** Autogenerated input type of UpsertPlaylist */
export type UpsertPlaylistInput = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: InputMaybe<Scalars['String']['input']>;
  /** 説明 */
  readonly description?: InputMaybe<Scalars['String']['input']>;
  /** タイトル */
  readonly name: Scalars['String']['input'];
  /** IDがない場合は作成 */
  readonly playlistId?: InputMaybe<Scalars['String']['input']>;
  /** 公開種別 */
  readonly publicType: PlaylistPublicTypeEnum;
  /** トラックID */
  readonly trackIds?: InputMaybe<ReadonlyArray<Scalars['String']['input']>>;
};

/** Autogenerated return type of UpsertPlaylist */
export type UpsertPlaylistPayload = {
  /** A unique identifier for the client performing the mutation. */
  readonly clientMutationId?: Maybe<Scalars['String']['output']>;
  /** 作成更新されたプレイリスト */
  readonly playlist?: Maybe<PlaylistObject>;
};

/** ユーザー */
export type UserObject = {
  /** ID */
  readonly id: Scalars['String']['output'];
  /** 名前 */
  readonly name: Scalars['String']['output'];
  /** ユーザー名 */
  readonly username: Scalars['String']['output'];
};

export type CurrentUserFieldsFragment = { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } };

export type PlaylistFieldsFragment = { readonly id: string, readonly name: string, readonly description: string, readonly publicType: PlaylistPublicTypeEnum, readonly isMine?: boolean | undefined, readonly createdAt: string, readonly updatedAt: string, readonly author?: { readonly id: string, readonly name: string, readonly username: string } | undefined, readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined, readonly items: ReadonlyArray<{ readonly trackNumber: number, readonly track: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } }> };

export type TrackFieldsFragment = { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } };

export type AddPlaylistItemsMutationVariables = Exact<{
  input: AddPlaylistItemsInput;
}>;


export type AddPlaylistItemsMutation = { readonly addPlaylistItems?: { readonly playlist?: { readonly id: string, readonly name: string, readonly description: string, readonly publicType: PlaylistPublicTypeEnum, readonly isMine?: boolean | undefined, readonly createdAt: string, readonly updatedAt: string, readonly author?: { readonly id: string, readonly name: string, readonly username: string } | undefined, readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined, readonly items: ReadonlyArray<{ readonly trackNumber: number, readonly track: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } }> } | undefined } | undefined };

export type ChangeAlbumStatusMutationVariables = Exact<{
  input: ChangeAlbumStatusInput;
}>;


export type ChangeAlbumStatusMutation = { readonly changeAlbumStatus?: { readonly result: boolean } | undefined };

export type ChangeArtistStatusMutationVariables = Exact<{
  input: ChangeArtistStatusInput;
}>;


export type ChangeArtistStatusMutation = { readonly changeArtistStatus?: { readonly result: boolean } | undefined };

export type ChangeFavoritesMutationVariables = Exact<{
  input: ChangeFavoritesInput;
}>;


export type ChangeFavoritesMutation = { readonly changeFavorites?: { readonly currentUser?: { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } } | undefined } | undefined };

export type ClearCacheMutationVariables = Exact<{
  input: ClearCacheInput;
}>;


export type ClearCacheMutation = { readonly clearCache?: { readonly result?: ReadonlyArray<string> | undefined } | undefined };

export type IgnoreAlbumsMutationVariables = Exact<{
  input: IgnoreAlbumsInput;
}>;


export type IgnoreAlbumsMutation = { readonly ignoreAlbums?: { readonly result?: boolean | undefined } | undefined };

export type IgnoreArtistsMutationVariables = Exact<{
  input: IgnoreArtistsInput;
}>;


export type IgnoreArtistsMutation = { readonly ignoreArtists?: { readonly result?: boolean | undefined } | undefined };

export type LoginMutationVariables = Exact<{
  input: LoginInput;
}>;


export type LoginMutation = { readonly login?: { readonly currentUser?: { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } } | undefined } | undefined };

export type LogoutMutationVariables = Exact<{
  input: LogoutInput;
}>;


export type LogoutMutation = { readonly logout?: { readonly currentUser?: { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } } | undefined } | undefined };

export type SignupMutationVariables = Exact<{
  input: SignupInput;
}>;


export type SignupMutation = { readonly signup?: { readonly currentUser?: { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } } | undefined } | undefined };

export type UpdateRoleMutationVariables = Exact<{
  input: UpdateRoleInput;
}>;


export type UpdateRoleMutation = { readonly updateRole?: { readonly role?: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> } | undefined } | undefined };

export type UpsertPlaylistMutationVariables = Exact<{
  input: UpsertPlaylistInput;
}>;


export type UpsertPlaylistMutation = { readonly upsertPlaylist?: { readonly playlist?: { readonly id: string, readonly name: string, readonly description: string, readonly publicType: PlaylistPublicTypeEnum, readonly isMine?: boolean | undefined, readonly createdAt: string, readonly updatedAt: string, readonly author?: { readonly id: string, readonly name: string, readonly username: string } | undefined, readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined, readonly items: ReadonlyArray<{ readonly trackNumber: number, readonly track: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } }> } | undefined } | undefined };

export type AlbumQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type AlbumQuery = { readonly album?: { readonly id: string, readonly totalTracks: number, readonly name: string, readonly status: StatusEnum, readonly releaseDate: string, readonly recordLabel: string, readonly copyright: string, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL?: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } | undefined, readonly artworkM?: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } | undefined, readonly tracks: ReadonlyArray<{ readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } }> } | undefined };

export type AlbumsQueryVariables = Exact<{
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<AlbumsSortInputObject>;
  conditions?: InputMaybe<AlbumsConditionsInputObject>;
}>;


export type AlbumsQuery = { readonly items?: ReadonlyArray<{ readonly id: string, readonly name: string, readonly status: StatusEnum, readonly artworkM?: { readonly url?: string | undefined } | undefined }> | undefined };

export type AllActionsQueryVariables = Exact<{ [key: string]: never; }>;


export type AllActionsQuery = { readonly allActions: ReadonlyArray<ActionEnum> };

export type AppleMusicTokenQueryVariables = Exact<{ [key: string]: never; }>;


export type AppleMusicTokenQuery = { readonly appleMusicToken: string };

export type ArtistQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type ArtistQuery = { readonly artist?: { readonly id: string, readonly name: string, readonly status: StatusEnum, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined };

export type ArtistsQueryVariables = Exact<{
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<ArtistsSortInputObject>;
  conditions?: InputMaybe<ArtistsConditionsInputObject>;
}>;


export type ArtistsQuery = { readonly items?: ReadonlyArray<{ readonly id: string, readonly name: string, readonly status: StatusEnum, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } }> | undefined };

export type MeQueryVariables = Exact<{ [key: string]: never; }>;


export type MeQuery = { readonly me: { readonly id: string, readonly name: string, readonly username: string, readonly registered: boolean, readonly role: { readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }, readonly favorite: { readonly albumIds: ReadonlyArray<string>, readonly artistIds: ReadonlyArray<string>, readonly trackIds: ReadonlyArray<string>, readonly playlistIds: ReadonlyArray<string> } } };

export type PlaylistQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type PlaylistQuery = { readonly playlist?: { readonly id: string, readonly name: string, readonly description: string, readonly publicType: PlaylistPublicTypeEnum, readonly isMine?: boolean | undefined, readonly createdAt: string, readonly updatedAt: string, readonly author?: { readonly id: string, readonly name: string, readonly username: string } | undefined, readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined, readonly items: ReadonlyArray<{ readonly trackNumber: number, readonly track: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } }> } | undefined };

export type PlaylistsQueryVariables = Exact<{
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<PlaylistsSortInputObject>;
  conditions?: InputMaybe<PlaylistsConditionsInputObject>;
}>;


export type PlaylistsQuery = { readonly items?: ReadonlyArray<{ readonly id: string, readonly name: string, readonly createdAt: string, readonly updatedAt: string, readonly author?: { readonly id: string, readonly name: string, readonly username: string } | undefined, readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined }> | undefined };

export type RolesQueryVariables = Exact<{ [key: string]: never; }>;


export type RolesQuery = { readonly roles: ReadonlyArray<{ readonly id: string, readonly name: string, readonly description: string, readonly allowedActions: ReadonlyArray<ActionEnum> }> };

export type TrackQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type TrackQuery = { readonly track?: { readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } } | undefined };

export type TracksQueryVariables = Exact<{
  cursor?: InputMaybe<CursorInputObject>;
  sort?: InputMaybe<TracksSortInputObject>;
  conditions?: InputMaybe<TracksConditionsInputObject>;
}>;


export type TracksQuery = { readonly items?: ReadonlyArray<{ readonly id: string, readonly isrc: string, readonly name: string, readonly status: StatusEnum, readonly discNumber: number, readonly trackNumber: number, readonly durationMs: number, readonly previewUrl?: string | undefined, readonly popularity: number, readonly appleMusicId: string, readonly appleMusicPlayable: boolean, readonly artworkL: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined }, readonly artworkM: { readonly url?: string | undefined, readonly width?: number | undefined, readonly height?: number | undefined } }> | undefined };

export const CurrentUserFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<CurrentUserFieldsFragment, unknown>;
export const TrackFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<TrackFieldsFragment, unknown>;
export const PlaylistFieldsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaylistFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"publicType"}},{"kind":"Field","name":{"kind":"Name","value":"isMine"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}}]}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<PlaylistFieldsFragment, unknown>;
export const AddPlaylistItemsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddPlaylistItems"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"AddPlaylistItemsInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addPlaylistItems"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playlist"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PlaylistFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaylistFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"publicType"}},{"kind":"Field","name":{"kind":"Name","value":"isMine"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}}]}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}}]}}]} as unknown as DocumentNode<AddPlaylistItemsMutation, AddPlaylistItemsMutationVariables>;
export const ChangeAlbumStatusDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ChangeAlbumStatus"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ChangeAlbumStatusInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"changeAlbumStatus"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"result"}}]}}]}}]} as unknown as DocumentNode<ChangeAlbumStatusMutation, ChangeAlbumStatusMutationVariables>;
export const ChangeArtistStatusDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ChangeArtistStatus"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ChangeArtistStatusInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"changeArtistStatus"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"result"}}]}}]}}]} as unknown as DocumentNode<ChangeArtistStatusMutation, ChangeArtistStatusMutationVariables>;
export const ChangeFavoritesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ChangeFavorites"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ChangeFavoritesInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"changeFavorites"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentUserFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<ChangeFavoritesMutation, ChangeFavoritesMutationVariables>;
export const ClearCacheDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ClearCache"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ClearCacheInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"clearCache"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"result"}}]}}]}}]} as unknown as DocumentNode<ClearCacheMutation, ClearCacheMutationVariables>;
export const IgnoreAlbumsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"IgnoreAlbums"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"IgnoreAlbumsInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ignoreAlbums"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"result"}}]}}]}}]} as unknown as DocumentNode<IgnoreAlbumsMutation, IgnoreAlbumsMutationVariables>;
export const IgnoreArtistsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"IgnoreArtists"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"IgnoreArtistsInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ignoreArtists"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"result"}}]}}]}}]} as unknown as DocumentNode<IgnoreArtistsMutation, IgnoreArtistsMutationVariables>;
export const LoginDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Login"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"LoginInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"login"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentUserFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<LoginMutation, LoginMutationVariables>;
export const LogoutDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Logout"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"LogoutInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"logout"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentUserFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<LogoutMutation, LogoutMutationVariables>;
export const SignupDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"Signup"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"SignupInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"signup"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"currentUser"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentUserFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<SignupMutation, SignupMutationVariables>;
export const UpdateRoleDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateRole"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateRoleInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateRole"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}}]}}]}}]} as unknown as DocumentNode<UpdateRoleMutation, UpdateRoleMutationVariables>;
export const UpsertPlaylistDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpsertPlaylist"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"UpsertPlaylistInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"upsertPlaylist"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playlist"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PlaylistFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaylistFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"publicType"}},{"kind":"Field","name":{"kind":"Name","value":"isMine"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}}]}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}}]}}]} as unknown as DocumentNode<UpsertPlaylistMutation, UpsertPlaylistMutationVariables>;
export const AlbumDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Album"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"album"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"totalTracks"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"releaseDate"}},{"kind":"Field","name":{"kind":"Name","value":"recordLabel"}},{"kind":"Field","name":{"kind":"Name","value":"copyright"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}},{"kind":"Field","name":{"kind":"Name","value":"tracks"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<AlbumQuery, AlbumQueryVariables>;
export const AlbumsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Albums"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"CursorInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"AlbumsSortInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"AlbumsConditionsInputObject"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"items"},"name":{"kind":"Name","value":"albums"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"cursor"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}},{"kind":"Argument","name":{"kind":"Name","value":"conditions"},"value":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}}]}}]}}]}}]} as unknown as DocumentNode<AlbumsQuery, AlbumsQueryVariables>;
export const AllActionsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AllActions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"allActions"}}]}}]} as unknown as DocumentNode<AllActionsQuery, AllActionsQueryVariables>;
export const AppleMusicTokenDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"AppleMusicToken"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"appleMusicToken"}}]}}]} as unknown as DocumentNode<AppleMusicTokenQuery, AppleMusicTokenQueryVariables>;
export const ArtistDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Artist"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"artist"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}}]}}]}}]} as unknown as DocumentNode<ArtistQuery, ArtistQueryVariables>;
export const ArtistsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Artists"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"CursorInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ArtistsSortInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ArtistsConditionsInputObject"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"items"},"name":{"kind":"Name","value":"artists"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"cursor"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}},{"kind":"Argument","name":{"kind":"Name","value":"conditions"},"value":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}}]}}]}}]} as unknown as DocumentNode<ArtistsQuery, ArtistsQueryVariables>;
export const MeDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Me"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"me"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CurrentUserFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CurrentUserFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CurrentUserObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}},{"kind":"Field","name":{"kind":"Name","value":"registered"}},{"kind":"Field","name":{"kind":"Name","value":"role"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}},{"kind":"Field","name":{"kind":"Name","value":"favorite"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"albumIds"}},{"kind":"Field","name":{"kind":"Name","value":"artistIds"}},{"kind":"Field","name":{"kind":"Name","value":"trackIds"}},{"kind":"Field","name":{"kind":"Name","value":"playlistIds"}}]}}]}}]} as unknown as DocumentNode<MeQuery, MeQueryVariables>;
export const PlaylistDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Playlist"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"playlist"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"PlaylistFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"PlaylistFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"publicType"}},{"kind":"Field","name":{"kind":"Name","value":"isMine"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}}]}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}}]}}]} as unknown as DocumentNode<PlaylistQuery, PlaylistQueryVariables>;
export const PlaylistsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Playlists"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"CursorInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistsSortInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"PlaylistsConditionsInputObject"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"items"},"name":{"kind":"Name","value":"playlists"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"cursor"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}},{"kind":"Argument","name":{"kind":"Name","value":"conditions"},"value":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"author"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"username"}}]}},{"kind":"Field","name":{"kind":"Name","value":"track"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<PlaylistsQuery, PlaylistsQueryVariables>;
export const RolesDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Roles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"roles"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"allowedActions"}}]}}]}}]} as unknown as DocumentNode<RolesQuery, RolesQueryVariables>;
export const TrackDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Track"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"id"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"track"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"id"},"value":{"kind":"Variable","name":{"kind":"Name","value":"id"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<TrackQuery, TrackQueryVariables>;
export const TracksDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"Tracks"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"CursorInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"TracksSortInputObject"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"TracksConditionsInputObject"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"items"},"name":{"kind":"Name","value":"tracks"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"cursor"},"value":{"kind":"Variable","name":{"kind":"Name","value":"cursor"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}},{"kind":"Argument","name":{"kind":"Name","value":"conditions"},"value":{"kind":"Variable","name":{"kind":"Name","value":"conditions"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TrackFields"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TrackFields"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"TrackObject"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"isrc"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"status"}},{"kind":"Field","name":{"kind":"Name","value":"discNumber"}},{"kind":"Field","name":{"kind":"Name","value":"trackNumber"}},{"kind":"Field","name":{"kind":"Name","value":"durationMs"}},{"kind":"Field","name":{"kind":"Name","value":"previewUrl"}},{"kind":"Field","name":{"kind":"Name","value":"popularity"}},{"kind":"Field","name":{"kind":"Name","value":"artworkL"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"artworkM"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"url"}},{"kind":"Field","name":{"kind":"Name","value":"width"}},{"kind":"Field","name":{"kind":"Name","value":"height"}}]}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicId"}},{"kind":"Field","name":{"kind":"Name","value":"appleMusicPlayable"}}]}}]} as unknown as DocumentNode<TracksQuery, TracksQueryVariables>;